import type {
    PanelTab,
    RolMeta,
    SayfaDef,
    UserFormState,
} from "../types";

export const ROLES: RolMeta[] = [
    { key: "admin", label: "Admin", color: "#111827", bg: "#f8fafc", border: "#d1d5db", icon: "ti-shield-lock", desc: "" },
    { key: "mudur", label: "Müdür", color: "#111827", bg: "#f8fafc", border: "#d1d5db", icon: "ti-briefcase", desc: "" },
    { key: "yonetici", label: "Yönetici", color: "#111827", bg: "#f8fafc", border: "#d1d5db", icon: "ti-user-check", desc: "" },
    { key: "kullanici", label: "Kullanıcı", color: "#111827", bg: "#f8fafc", border: "#d1d5db", icon: "ti-user", desc: "" },
];

export const PAGES: SayfaDef[] = [
    {
        key: "anasayfa",
        label: "Anasayfa",
        path: "/anasayfa",
        grup: "Genel",
        columns: ["Dashboard Kartları", "Toplam Sipariş", "Aktif Araçlar", "Tamamlanan Sefer"],
        buttons: ["new_order", "go_planlama", "go_manuel", "go_araclar"],
    },
    {
        key: "bim_planlama",
        label: "Planlama",
        path: "/bimafyon/planlama",
        grup: "BİM AFYON",
        columns: [
            "Sefer No", "Sevk Tarihi", "Yükleyen Depo", "Kalkış Yeri", "Araç Cinsi",
            "Çekici", "Dorse", "Sürücü", "Telefon", "Varış 1", "Varış 2", "Varış 3",
            "Varış 4", "Palet", "Navlun", "Rota", "Durak Sayısı", "Doluluk %",
        ],
        buttons: [
            "data_file_upload",
            "demand_file_upload",
            "planla",
            "arac_ekle",
            "arac_sil",
            "durak_ekle",
            "durak_sil",
            "baska_araca_tasi",
            "baska_sefere_al",
            "araca_geri_al",
            "arac_maliyeti_duzenle",
            "ozet_goster",
            "json_export",
            "aktif_sefere_aktar",
        ],
    },
    {
        key: "bim_manuel",
        label: "Manuel Sipariş",
        path: "/bimafyon/manuelsiparis",
        grup: "BİM AFYON",
        columns: [
            "Sevk Tarihi",
            "Müşteri / Firma",
            "Varış 1",
            "Varış 2",
            "Varış 3",
            "Varış 4",
            "Palet",
            "Araç Cinsi",
            "Açıklama",
            "Kaynak",
        ],
        buttons: [
            "excel_import",
            "add_order",
            "delete_order",
            "clear",
            "goto_plate",
        ],
    },
    {
        key: "bim_aktif",
        label: "Aktif Seferler",
        path: "/bimafyon/aktifseferler",
        grup: "BİM AFYON",
        columns: [
            "id",
            "seferNo",
            "sevkTarihi",
            "yukleyenDepo",
            "kalkisYeri",
            "aracCinsi",
            "cekici",
            "dorse",
            "tc",
            "surucu",
            "telefon",
            "faturaVkn",
            "varis1",
            "varis2",
            "varis3",
            "varis4",
            "palet",
            "irsaliyeNo",
            "datalogerNo",
            "freshlianceBattery",
            "freshlianceLocation",
            "freshlianceUpdatedAt",
            "freshlianceTemperature",
            "navlun",
            "aracDurumu",
            "peronNo",
        ],
        buttons: [
            "actions",
            "export_excel",
            "import_excel",
            "irsaliye",
            "bulk_complete",
            "view_settings",
            "delete",
            "select_vehicle",
            "update_vkn",
        ],
    },
    {
        key: "bim_silinen",
        label: "Silinen Seferler",
        path: "/bimafyon/silinenseferler",
        grup: "BİM AFYON",
        columns: [
            "Eski ID", "Sefer No", "Çekici", "Sürücü", "Varış", "Durum",
            "Silinme Nedeni", "Silen Kullanıcı", "Tarih",
        ],
        buttons: [
            "refresh",
            "export_excel",
            "copy_json",
        ],
    },
    {
        key: "bim_tamamlanan",
        label: "Tamamlanan",
        path: "/bimafyon/tamamlananseferler",
        grup: "BİM AFYON",
        columns: [
            "Eski ID", "Sefer No", "Çekici", "Dorse", "Sürücü", "Telefon",
            "Varış", "İrsaliye", "Tamamlayan", "Tarih",
        ],
        buttons: [
            "refresh",
            "detail",
            "export_excel",
            "copy_json",
        ],
    },
    {
        key: "araclar",
        label: "Araç Yönetimi",
        path: "/aracyonetimi/araclar",
        grup: "Araç Yönetimi",
        columns: ["Sürücü", "Çekici Plaka", "Dorse Plaka", "TC", "Telefon", "VKN", "Dataloger No"],
        buttons: [
            "create_vehicle",
            "edit_vehicle",
            "delete",
            "export_excel",
            "card_view",
        ],
    },
    {
        key: "donus_siparis",
        label: "Sipariş",
        path: "/donusler/siparis",
        grup: "Dönüşler",
        columns: ["Müşteri", "Yükleme Yeri", "Teslim Yeri", "Navlun", "Sevk Tarihi"],
        buttons: [
            "new_value",
            "select_customer",
            "select_route",
            "preview_order",
            "open_orders",
            "refresh",
        ],
    },
    {
        key: "donus_plaka",
        label: "Plaka Atama",
        path: "/donusler/plakaatama",
        grup: "Dönüşler",
        columns: [
            "Sefer No", "Sevk Tarihi", "Yükleyen Depo", "Kalkış Yeri", "Çekici",
            "Dorse", "TC", "Sürücü", "Telefon", "VKN", "Varış 1", "Varış 2",
            "Varış 3", "Varış 4", "Palet", "İrsaliye", "Dataloger No", "Navlun",
            "Araç Durumu", "Peron No",
        ],
        buttons: [
            "import_excel",
            "export_excel",
            "irsaliye",
            "select_vehicle",
            "change_driver",
            "delete_trip",
            "complete_trip",
            "show_map",
        ],
    },
    {
        key: "donus_tamamlanan",
        label: "Tamamlanan",
        path: "/donusler/tamamlananseferler",
        grup: "Dönüşler",
        columns: [
            "Tamamlanma Tarihi", "Sefer No", "Sevk Tarihi", "Çekici", "Dorse",
            "Sürücü", "Telefon", "İrsaliye", "Navlun", "Tamamlayan",
        ],
        buttons: [
            "refresh",
            "export_excel",
            "copy_json",
        ],
    },
    {
        key: "donus_navlun",
        label: "Navlunlar",
        path: "/donusler/navlunlar",
        grup: "Dönüşler",
        columns: ["Müşteri Adı", "Yükleme Yeri", "Teslim Yeri", "Navlun"],
        buttons: [
            "create",
            "edit",
            "update",
            "delete",
        ],
    },
    {
        key: "ekkayit_vkn",
        label: "VKN",
        path: "/ekkayitlar/vkn",
        grup: "Ek Kayıtlar",
        columns: ["VKN", "Kullanım Sayısı"],
        buttons: [
            "create",
            "edit",
            "update",
            "delete",
        ],
    },
    {
        key: "ekkayit_ugrama",
        label: "Uğrama",
        path: "/ekkayitlar/ugrama",
        grup: "Ek Kayıtlar",
        columns: ["VKN", "Müşteri / Tip", "Tutar", "Durum"],
        buttons: [
            "toggle_depo",
            "update_amount",
            "change_status",
        ],
    },
    {
        key: "ekkayit_navlun",
        label: "Navlun",
        path: "/ekkayitlar/navlun",
        grup: "Ek Kayıtlar",
        columns: ["ID", "Varış 1", "Varış 2", "Varış 3", "Fiyat", "Durum", "Kayıt"],
        buttons: [
            "edit_row",
            "save",
            "cancel",
            "change_status",
            "update_price",
        ],
    },
];

export const EMPTY_USER_FORM: UserFormState = {
    id: "",
    name: "",
    email: "",
    password: "",
    dept: "",
    role: "kullanici",
    aktif: true,
};

export const TABS: { key: PanelTab; label: string; icon: string; desc: string }[] = [
    { key: "kullanicilar", label: "Kullanıcılar", icon: "ti-users", desc: "" },
    { key: "yetkilendirme", label: "Yetkilendirme", icon: "ti-shield-check", desc: "" },
    { key: "tumYetkiler", label: "Tüm Yetkiler", icon: "ti-list-check", desc: "" },
    { key: "loglar", label: "Loglar", icon: "ti-history", desc: "" },
    { key: "ayarlar", label: "Ayarlar", icon: "ti-settings", desc: "" },
];

export const PERMISSION_LABELS: Record<string, string> = {
    page: "Sayfayı Gör",

    // Ortak
    actions: "Satır İşlemleri",
    export_excel: "Excel Aktar",
    import_excel: "Excel İçe Aktar",
    excel_import: "Excel Verisi Aktar",
    view_settings: "Sütun Ayarları",
    delete: "Sil",
    edit: "Düzenle",
    save: "Kaydet",
    cancel: "Vazgeç",
    refresh: "Yenile",
    detail: "Detay",
    create: "Yeni Kayıt",
    update: "Güncelle",
    copy_json: "JSON Kopyala",

    // Anasayfa
    new_order: "Yeni Sipariş",
    go_planlama: "Planlama",
    go_manuel: "Manuel Sipariş",
    go_araclar: "Araçlar",

    // Aktif Seferler
    irsaliye: "İrsaliye Okut",
    bulk_complete: "Toplu Tamamla",
    select_vehicle: "Araç Seç",
    update_vkn: "Şoför / VKN Güncelle",

    // Planlama
    data_file_upload: "Veri Dosyası Yükle",
    demand_file_upload: "Talep Dosyası Yükle",
    planla: "Planlamayı Çalıştır",
    arac_ekle: "Araç Ekle",
    arac_sil: "Aracı Sil",
    durak_ekle: "+ Durak",
    durak_sil: "Durak Sil",
    baska_araca_tasi: "Başka Araca Taşı",
    baska_sefere_al: "Başka Sefere Al",
    araca_geri_al: "Araca Geri Al",
    arac_maliyeti_duzenle: "Araç Maliyeti Düzenle",
    ozet_goster: "Özeti Göster/Gizle",
    json_export: "JSON İndir",
    aktif_sefere_aktar: "Aktif Sefere Aktar",

    // Manuel Sipariş
    add_order: "Siparişi Listeye Ekle",
    delete_order: "Sipariş Sil",
    clear: "Listeyi Temizle",
    goto_plate: "Plaka Atamaya Geç",

    // Araç Yönetimi
    create_vehicle: "Yeni Araç",
    edit_vehicle: "Araç Düzenle",
    card_view: "Kart/Tablo Görünümü",

    // Dönüş Sipariş
    new_value: "Yeni Değer Ekle",
    select_customer: "Müşteri Seç",
    select_route: "Rota Seç",
    preview_order: "Siparişi Önizlemeye Ekle",
    open_orders: "Siparişleri Aç",

    // Plaka Atama
    change_driver: "Şoför Değiştir",
    delete_trip: "Sefer Sil",
    complete_trip: "Sefer Tamamla",
    show_map: "Haritada Göster",

    // Uğrama / Navlun
    toggle_depo: "İkiz Depo Şartını Aç/Kapat",
    update_amount: "Tutar Güncelle",
    change_status: "Durum Değiştir",
    edit_row: "Satırı Düzenle",
    update_price: "Fiyat Güncelle",

    // Kolonlar
    id: "ID",
    seferNo: "Sefer No",
    sevkTarihi: "Sevk Tarihi",
    yukleyenDepo: "Yükleyen Depo",
    kalkisYeri: "Kalkış Yeri",
    aracCinsi: "Araç Cinsi",
    cekici: "Çekici",
    dorse: "Dorse",
    tc: "TC",
    surucu: "Sürücü",
    telefon: "Telefon",
    faturaVkn: "Fatura VKN",
    varis1: "Varış 1",
    varis2: "Varış 2",
    varis3: "Varış 3",
    varis4: "Varış 4",
    palet: "Palet",
    irsaliyeNo: "İrsaliye No",
    datalogerNo: "Dataloger No",
    freshlianceBattery: "Batarya",
    freshlianceLocation: "Konum",
    freshlianceUpdatedAt: "Son Güncelleme",
    freshlianceTemperature: "Sıcaklık",
    navlun: "Navlun",
    aracDurumu: "Araç Durumu",
    peronNo: "Peron No",
};